modLoader = "javafml"
loaderVersion = "[43,)"
license="${mod_license}"

[[mods]]
modId = "archaeology"
displayTest="IGNORE_ALL_VERSION"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
itemIcon = "minecraft:brush"

[[dependencies.archaeology]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archaeology]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"